
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: shelbykelly_development

test:
  <<: *default
  database: shelbykelly_test

production:
  <<: *default
  database: shelbykelly_production
